### ISSUE TITLE
Trying to run ModelDumper

### ISSUE THREAD

**Issue by ZDongV** [im-frizzy/OpenRS#11]
Getting the following when trying to run ModelDumper 

  Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 33
	  at net.openrs.cache.ReferenceTable.decode(ReferenceTable.java:475)
	  at net.openrs.cache.Cache.<init>(Cache.java:76)
	  at net.openrs.cache.tools.ModelDumper.main(ModelDumper.java:48)
 
  Process finished with exit code 1

This is just after building in IntelliJ and dropping OSRS cache files in /repository/cache/

My /cache/ directory:
![image](https://user-images.githubusercontent.com/47888112/57383628-05a9c500-71a7-11e9-9f71-f3447659c404.png)

Any ideas? Am I doing something stupid

**Comment by ZDongV** [comment]
Hi I've possibly found a fix to this - took cache files from a PC who hadn't ran RS client in a while (since 29-Dec-18) and it seemed to work with these. So looks like the current OSRS cache files do not work with this?

**Comment by AshGreh** [comment]
@ZDongV that happens mainly because the child's value(used as index) in the loop is out of bounds for the given array. The current member that causes it skips number 29. The way around it would be to either change the array size or use a dynamic collection of values that allows skipping indexes.

**Comment by Joshua-F** [comment]
Go to `ReferenceTable` and where it decodes child identifiers, replace that whole thing with this. The issue is that they usually don't skip ids, and the last child happens to be the one that has the higher id. This fixes it by making the array the proper size based on the highest child id.
```java
		/* read the child identifiers if present */
		if ((table.flags & FLAG_IDENTIFIERS) != 0) {
			for (final int id : ids) {

				/* added block of code */
				int length = members[id][0];
				{
					for (final int child : members[id]) {
						if (child > length) {
							length = child;
						}
					}
					length++;
				}

				identifiersArray = new int[/*members[id].length*/length];
				for (final int child : members[id]) {
					final int identifier = buffer.getInt();
					identifiersArray[child] = identifier;
					table.entries.get(id).entries.get(child).identifier = identifier;
				}
				table.entries.get(id).identifiers = new Identifiers(identifiersArray);
			}
		}
```

**Comment by anthonyloukinas** [comment]
> Go to `ReferenceTable` and where it decodes child identifiers, replace that whole thing with this. The issue is that they usually don't skip ids, and the last child happens to be the one that has the higher id. This fixes it by making the array the proper size based on the highest child id.
> 
> ```java
> 		/* read the child identifiers if present */
> 		if ((table.flags & FLAG_IDENTIFIERS) != 0) {
> 			for (final int id : ids) {
> 
> 				/* added block of code */
> 				int length = members[id][0];
> 				{
> 					for (final int child : members[id]) {
> 						if (child > length) {
> 							length = child;
> 						}
> 					}
> 					length++;
> 				}
> 
> 				identifiersArray = new int[/*members[id].length*/length];
> 				for (final int child : members[id]) {
> 					final int identifier = buffer.getInt();
> 					identifiersArray[child] = identifier;
> 					table.entries.get(id).entries.get(child).identifier = identifier;
> 				}
> 				table.entries.get(id).identifiers = new Identifiers(identifiersArray);
> 			}
> 		}
> ```

This worked for me!

**Comment by kfricilone** [comment]
see d2fd4701f2f938b758642e4133c039c2417defdb
